all	: osc2u.e urqmd.e

osc2u.e:
	$(MAKE) -C osc2u

urqmd.e:
	$(MAKE) -C urqmd

clean:
	$(MAKE) -C osc2u clean
	$(MAKE) -C urqmd clean

distclean:
	$(MAKE) -C osc2u distclean
	$(MAKE) -C urqmd distclean
